spring.application.name=connector

# Kafka
kafka.bootstrap-servers=localhost:9092
kafka.topic.raw=market.data.raw
kafka.topics.subscription-state=market.subscriptions
kafka.producer.acks=all
kafka.producer.linger-ms=5
kafka.producer.batch-size=16384

# Exchange Rate Limits
exchange.rate-limit.delay-ms=50

# Server
server.port=5556
