spring.application.name=connector
server.port=5556

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.acks=all
spring.kafka.producer.compression-type=lz4
spring.kafka.producer.batch-size=32768

kafka.topics.raw=market.data.raw
kafka.topics.subscription-state=market.subscriptions

